export const items = [
  {
    title: 'item one',
    available: true,
    price: '99,50',
    discount: '20',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item two',
    available: true,
    price: '109,50',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item three',
    available: true,
    price: '99,50',
    discount: '10',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item four',
    available: false,
    price: '49,50',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item five',
    available: true,
    price: '29,50',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item six',
    available: false,
    price: '69,50',
    discount: '45',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
  {
    title: 'item seven',
    available: true,
    price: '19,50',
    discount: '10',
    imageSrc: 'src/assets/images/iphone15.jpeg',
    imageAlt: 'iphone',
    link: '/',
  },
];
